global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

  #slack_api_url: ''

route:
  receiver: "db-alert-email"
  group_by: ['env','instance','type','group','job']
  group_wait:      30s
  group_interval:  3m
  repeat_interval: 3m
  routes:
 # - match:
 #     env: test-cluster
 #   receiver: db-alert-slack
  - match:
      env: test-cluster
    receiver: db-alert-email

receivers:

#- name: 'db-alert-slack'
#  slack_configs:
#  - channel: '#alerts'
#    username: 'db-alert'
#    icon_emoji: ':bell:'
#    title:   '{{ .CommonLabels.alertname }}'
#    text:    'in {{ .CommonLabels.env}}:   {{ .GroupLabels.alertname }}  {{ .CommonAnnotations.description }}      http://172.0.0.1:9093/alerts'

- name: 'db-alert-email'
  email_configs:
  - send_resolved: false
    to: 'xxx@xxx.com'
